language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'

services:
  - mysql
  - npm

before_install:
  - mysql -e 'CREATE DATABASE gitchallenge;'

before_script:
  - cp include/configuration-template.php include/configuration.php
  - npm install
  - npm install -g bower
  - bower install

script:
  - phpunit test.php
